### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by antondalgren** [elbywan/crystalline#6]
I'm running crystalline within a fairly large project. The CPU usage is pending between 20% and 60% with the codebase completely idle. Upon a save it can reach more than 200% (Using `top` on OSX to read these values)

**Comment by elbywan** [comment]
Hi @antondalgren,

> Upon a save it can reach more than 200% (Using top on OSX to read these values)

Yes, `Crystalline` (and by extension the crystal compiler that is used under the hood) is CPU intensive which could only be changed if someone takes time to add incremental semantic analysis. I have an idea about how to do it, but I don't have the bandwidth to work on it unfortunately (and it is pretty intensive work).

> The CPU usage is pending between 20% and 60% with the codebase completely idle.

Are you sure that this CPU usage comes from crystalline itself? Personally I had to downgrade VSCode from  >= 1.50.0 back to 1.49.X because the vscode rendering process was doing exactly that.

**Comment by antondalgren** [comment]
I'm running 1.49.3. Since monday this problem stopped occurring.

Most likely not a problem with crystalline!

Thank you for your time and the keep up the good work on this @elbywan!
