### ISSUE TITLE
Neovim LspInstall error - name of the file 

### ISSUE THREAD

**Issue by calebdiaz** [elbywan/crystalline#62]
Downloading file "https://github.com/elbywan/crystalline/releases/download/v0.8.0/crystalline_x86_64-unknown-linux-gnu.gz"...

Failed to download file

current release is -musl.gz instead of -gnu.gz

**Comment by elbywan** [comment]
Hey @calebdiaz,

I am not sure I can do anything about this. I do not maintain any of the neovie related plugins.

**Comment by calebdiaz** [comment]
Hi
Maybe a link with that name to the same file? I don't know if it is even possible.

**Comment by elbywan** [comment]
> Maybe a link with that name to the same file? I don't know if it is even possible.

I do not think that would be accurate anyway, I renamed from `-gnu` to `-musl` for a good reason, because the binary is compiled with the musl stdlib and using gnu was just wrong : https://github.com/elbywan/crystalline/issues/50#issuecomment-1313613688

I do not know how the neovim plugin works under the hood, if the binary url is written somewhere or whatever but I think that the problem comes from their side. (maybe here? https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/servers/crystalline/init.lua#L22)

**Comment by calebdiaz** [comment]
Listen it's not because I need it. I know how to install it manually.
If you don't care that people won't be able to use it easily... ┐(シ)┌
thanks!

**Comment by elbywan** [comment]
Again, it’s not that I do not care. It’s just the wrong place to open an issue.

I have no relationship with anything neovim related whatsoever. There is nothing I can do if the url they use is wrong.
