### ISSUE TITLE
Move Crystalline to LSProtocol

### ISSUE THREAD

**Issue by nobodywasishere** [elbywan/crystalline#97]
LSProtocol is a repo with auto-generated types for the language server protocol, which I have added Crystal support to [here](https://github.com/nobodywasishere/lsprotocol) (and an external shard [here](https://github.com/nobodywasishere/lsprotocol-crystal)). Being auto-generated, it makes adding new functionality really easy, and is the basis of development for [larimar](https://github.com/nobodywasishere/larimar).

Moving crystalline to this would involve moving the server component of elbywan/lsp into crystalline itself, but would allow for more control of the server as a whole, alongside not needing to figure out the LSP API itself (on a protocol level).

If you would be interested in this, I'd be happy to port crystalline over and create a PR. Feedback is also welcome.

**Comment by elbywan** [comment]
Hey, thanks for reaching out but I am not interested.

See: https://github.com/elbywan/crystalline?tab=readme-ov-file#project-status

**Comment by and3md** [comment]
> See: https://github.com/elbywan/crystalline?tab=readme-ov-file#project-status

I just read the readme. It's sad that someone treated you that way. I've been using Crystalline for a few months. For me, if there were no LSP server, I probably wouldn't have gotten interested in the Crystal language. Sometimes autocompletion doesn't work - I haven't figured out when exactly. But even so, it's very useful. Despite everything, I believe there are more users who appreciate your work (like me), even if they might not be vocal about it.

**Comment by phil294** [comment]
I'm not so sure about the trash-talk thing, but man I really wished the Crystal team valued this project more. There's a trend of modern languages treating LSP as a first-class citizen, but Crystal isn't one of them. IMO it's got the biggest leverage for fixing the language's popularity, above Windows support.

Crystalline already is a fantastic project. It's the de-facto standard tooling for the language and like most people, I use it exclusively when developing in Crystal. Once you've set it up, it works outstandingly well, given the heavy constraints the language must pose you. Yet somehow nobody in the ecosystem actually cares for it. It's so weird.

Thanks for your work elbywan!

**Comment by zw963** [comment]
> I'm not so sure about the trash-talk thing, but man I really wished the Crystal team valued this project more. There's a trend of modern languages treating LSP as a first-class citizen, but Crystal isn't one of them. IMO it's got the biggest leverage for fixing the language's popularity, above Windows support.
> 
> Crystalline already is a fantastic project. It's the de-facto standard tooling for the language and like most people, I use it exclusively when developing in Crystal. Once you've set it up, it works outstandingly well, given the heavy constraints the language must pose you. Yet somehow nobody in the ecosystem actually cares for it. It's so weird.
> 
> Thanks for your work elbywan!

Totally agree with you!

I don't know why the Crystal core team was so hasty, I had mentioned it multiple times on the forum before, they spend too much resources on (unpopular) Windows, while they don't care about the actual users' experience.

Some responsible language, LSP is even part of language itself, but, i consider Crystal core team never really considered supporting it.

**Comment by mjblack** [comment]
> @zw963 
> I don't know why the Crystal core team was so hasty, I had mentioned it multiple times on the forum before, they spend too much resources on (unpopular) Windows, while they don't care about the actual users' experience.

I wasnt going to respond to this closed thread but seeing the comment about Windows, as a dev using crystal with Windows and with linux/unix/macos.

Windows support is critical, just like linux/unix/macos, to the success of Crystal. If there was no windows support then that would push potential crystal users to other languages. With all that said, I believe that Crystalline is also critical to the success of the language. The only reason I currently am not using Crystalline is due to a bug. I came here looking to see if there was a reported issue, and a workaround.

> @elbywan 
> Hey, thanks for reaching out but I am not interested.
> See: https://github.com/elbywan/crystalline?tab=readme-ov-file#project-status

Sometimes I wonder if people want Crystal to be relegated to a niche language. I constantly hear in the discord about how Crystal has no tools but IMHO Crystalline is one of those tools needed for the success of the language, and $${\color{red}it \space makes \space me \space angry}$$ that people are actively being discouraged from using it. 

@elbywan I'm sorry that your work is not being appreciated by more in the community. ☹️
